Added a GetUnsignedInteger function for getting unsigned values.
benhoyt/inih pull request #147
Opened 2022-11-18 20:28 UTC by jcormier

2022-11-19 01:33 UTC, benhoyt requested changes
Thanks! I'm good with adding this, though let's call it `GetUnsigned` as mentioned. Also, as you can see by the failed test output, you need to update `examples/cpptest.txt` so the C++ test passes.

2022-11-19 01:33 UTC, benhoyt commented on cpp/INIReader.cpp
> +unsigned long INIReader::GetUnsignedInteger(const string& section, const string& name, unsigned long default_value) const
Let's call this `GetUnsigned` for brevity (like with C / C++ itself, the "integer" is kind of obvious).
```suggestion
unsigned long INIReader::GetUnsigned(const string& section, const string& name, unsigned long default_value) const
```

2022-11-19 01:33 UTC, benhoyt commented on cpp/INIReader.h
> +    // not found or not a valid integer (decimal "1234", or hex "0x4d2").
Let's wrap these comment lines at <80 chars, so after "returning" and after "or".

2022-11-19 01:34 UTC, benhoyt commented
Also, please update the PR title, and add a PR description (ideally with your use case).

2022-11-22 14:50 UTC, jcormier commented
Thanks for the feedback. Working on it from my phone 😆. We shall see how that goes. I'll post another update when im done.

2022-11-22 16:03 UTC, jcormier commented
Alright changes made. I'd like to squash all these commits together but can't seem to from the phone. So I'll get back to it next week when im back at my computer. Unless your dive with it as is

2022-11-22 19:20 UTC, benhoyt commented on cpp/INIReader.h
> +    INI_API unsigned long GetUnsignedInteger(const std::string& section, const std::string& name, unsigned long default_value) const;
```suggestion
    INI_API unsigned long GetUnsigned(const std::string& section, const std::string& name, unsigned long default_value) const;
```

2022-11-22 19:28 UTC, benhoyt commented
Thanks. Two further changes required: 1) change `GetUnsignedInteger` to `GetUnsigned` in the header file too, and 2) update `examples/cpptest.txt` so the C++ test passes.

2022-11-28 15:07 UTC, jcormier commented
Updated and squashed commits

2022-11-28 19:25 UTC, merged

2022-11-28 19:25 UTC, benhoyt commented
Thanks!